apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-image-tag
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: pod-containers-must-not-use-latest
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: Container images must not use the latest tag.
        foreach:
          - list: request.object.spec.containers
            deny:
              conditions:
                any:
                  - key: "{{ regex_match('^.*:latest$', element.image) }}"
                    operator: Equals
                    value: true
