apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: pods-must-run-as-non-root
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: Pods must set runAsNonRoot at the pod level and container level.
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
            containers:
              - securityContext:
                  runAsNonRoot: true
